### PR TITLE
fix: disable husky

### LINKED ISSUE #2: Fix CI error
See: https://github.com/node-casbin/mongo-changestream-watcher/actions/runs/2927758423

image

### PR DESCRIPTION
**Pull request by Sefriol**
@hsluoyz Enable codebeat by logging into [codebeat.co](https://codebeat.co/) and add mongo-changestream-watcher there. I cannot since I do not have a repository admin role.

Need to double check that the codebeat badge is also correct. I updated code coverage to the correct one and it should be now working. However I think you need to enable [coveralls.io](https://docs.coveralls.io/coveralls-notifications) from their website for it to be directly available in the pull requests.

Fix: https://github.com/node-casbin/mongo-changestream-watcher/issues/2

### CODE REVIEW

**Comment by Sefriol** [comment]
https://github.com/node-casbin/mongo-changestream-watcher/runs/8033886914?check_suite_focus=true#step:5:30

Husky is disabled now, so it should work.

**Comment by Sefriol** [comment]
> ## Pull Request Test Coverage Report for [Build 2932803006](https://coveralls.io/builds/51974060)
> * **0** of **0**   changed or added relevant lines in **0** files are covered.
> * No unchanged relevant lines lost coverage.
> * Overall coverage decreased (**-100.0%**) to **0.0%**
> 
> Totals	[Coverage Status](https://coveralls.io/builds/51974060)
> Change from base [Build 2931524098](https://coveralls.io/builds/51968128):	-100.0%
> Covered Lines:	0
> Relevant Lines:	0
> ##### 💛 - [Coveralls](https://coveralls.io)

Ehm, why does it report it like this...

**Comment by hsluoyz** [comment]
@Sefriol 

Codebeat: https://codebeat.co/projects/github-com-node-casbin-mongo-changestream-watcher-master

Coveralls: https://coveralls.io/github/node-casbin/mongo-changestream-watcher

Let me know if you need anything else

**Comment by Sefriol** [comment]
@hsluoyz I think only the npm stuff is left. Does the `semantic-release` take care of the npm repository creation or does it need to be configured manually first?

Current package name defined [here](https://github.com/node-casbin/mongo-changestream-watcher/blob/master/package.json#L2).

Links added in [README](https://github.com/node-casbin/mongo-changestream-watcher/blob/master/README.md?plain=1#L10). Might be incorrect.

**Comment by hsluoyz** [comment]
@Sefriol created here: https://www.npmjs.com/package/@casbin/mongo-changestream-watcher

Now it can accept new release pushes from CI

**Pull request merged**
